version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /tests
    package-ecosystem: pip
    schedule:
      interval: monthly
      day: saturday
    groups:
      python-test-dependencies:
        patterns:
          - "*"
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /scripts/linkbot/
    package-ecosystem: npm
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
